### PR TITLE
 Updated to work with Webpack v2.2.1

### PR DESCRIPTION
**Pull request by morficus**
~~`exports` is now `__webpack_exports__` (ref: webpack/webpack#3580)~~

as of 2.2.0-RC5, `exports` is `__webpack_exports__` only when dealing with Harmony modules (ref: https://github.com/webpack/webpack/pull/3958/files#diff-8cd2eded03d42fd1bec15366a1151fb5R32)

### CODE REVIEW

**Comment by morficus** [comment]
Prior to making this fix, trying to load the WebPack bundle would result in the following error:
```
Uncaught (in promise) Error: exports is not defined
```

**Comment by internettrans** [comment]
Thanks for the fix for this! Is `__webpack_exports__` defined in webpack 1 as well? If not, then could we get this to work with both webpack 1 and webpack 2 by detecting which version of webpack is being used in order to determine whether to use `exports` or `__webpack_exports__`?

**Comment by morficus** [comment]
This change was introduced during one of the 2.2 RCs, so I'm sure it's not the same in 1.x.

I'll have to do some type of research see how to determine 1.x vs 2.x at run-time.

**Comment by morficus** [comment]
@joeldenning the PR has been updated.
Turns out I originally got it wrong... `__webpack_exports__` doesn't apply across the board in v2.2... it only comes in to play when dealing with Harmony modules in v2.2.

So I updated the PR to set the proper text based on the module type.

**Comment by internettrans** [comment]
Thanks for your help with this. Published as v1.5.0

**Pull request merged**
